site_name: Apunte Programaci√≥n Concurrente
repo_url: https://github.com/nicopinera/concurrente
theme:
  name: material
  custom_dir: docs/overrides

nav:
  - Inicio: index.md
  - Temario: materia-apunte/temario.md
  - Unidades:
      - Unidad 1: unidades/u1-introduccion.md
      - Unidad 2: unidades/u2-sincronizacion.md
      - Unidad 3: unidades/u3-gramatica.md
      - Unidad 4: unidades/u4-bases_redes_petri.md
      - Unidad 5: unidades/u5-propiedades_redes_petri.md
      - Unidad 6: unidades/u6-monitor-concurrencia.md
      - Unidad 7: unidades/u7-regex.md
      - Unidad 8: unidades/u8-Apuntes-practicos.md
      - Unidad 9: unidades/u9-intro-java.md
  - Preguntas Coloquio: materia-apunte/preguntas_coloqui.md

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.tabbed
  - admonition

plugins:
  - awesome-pages
  - glightbox
  - minify
